# This is a Docker Compose configuration for production use.
# For building locally use docker-compose.yaml

# Run all services:
# docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up --pull always --detach

# Override the default settings for production
services:
  bot:
    # Pull the image from GitHub Container Registry instead of building locally
    image: 'ghcr.io/one-zero-eight/sport-bot:${DOCKER_TAG_BOT:-main}'
    build: !reset null
    env_file: .env.bot

  prisma-migrate:
    # Pull the image from GitHub Container Registry instead of building locally
    image: 'ghcr.io/one-zero-eight/sport-bot:${DOCKER_TAG_BOT:-main}'
    build: !reset null
    env_file: .env.bot

  db:
    ports: !reset [] # Do not expose any ports
    env_file: .env.db
