name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        id: dependencies
        run: pnpm install

      - name: Generate Prisma client code
        run: cd backend && pnpm run prisma:generate

      - name: Typecheck
        if: '!cancelled()'
        run: cd backend && pnpm run typecheck

      - name: Lint
        if: '!cancelled()'
        run: pnpm run lint

      - name: Test
        if: '!cancelled()'
        run: pnpm run test
